---
- name: Emergency shutdown of all rippled altnet validators
  hosts: all
  user: ubuntu
  sudo: true
  gather_facts: false
  vars_prompt:
    confirm: "Are you sure you want to kill the testnet!?! [y/N]"
  tasks:
    - name: Kill rippled
      command: pkill -9 rippled
      when: "confirm == 'y'"
