---
- name: Run RPC command on all validators
  hosts: all
  user: ubuntu
  gather_facts: false
  vars_prompt:
    rpc_command: "RPC command"
  vars:
    jq_filter: ""
  tasks:
    - name: Execute {{rpc_command}}
      shell: rippled --conf /etc/rippled/rippled.cfg -q '{{rpc_command}}' | jq .result.info{{jq_filter}}
      register: result
    - name: Print result
      debug: var=result.stdout
