---
- name: Install and configure a rippled validator
  hosts: all
  serial: "10%"
  user: ubuntu
  sudo: true
  gather_facts: false
  roles:
    - role: rippled
      vars:
        rippled_ssl_cert: ../skynet-keys/server.crt
        rippled_ssl_key: ../skynet-keys/server.key
        rippled_data_root: /mnt/rippled/db/
        rippled_log_file: /mnt/rippled/log/debug.log
        rippled_config_template: ../rippled.cfg
        rippled_run_service: false
  pre_tasks:
    - name: Make rippled data directories
      file: state=directory owner=rippled group=rippled path=/mnt/rippled/db/
    - name: Make rippled log directory
      file: state=directory owner=rippled group=rippled path=/mnt/rippled/log/
  tasks:
    - include: ../tasks/reconfigure-rippled.yml
