- name: Restart rippled on all validators
  hosts: all
  user: ubuntu
  sudo: true
  serial: "10%"
  gather_facts: false
  tasks:
    - name: Install apt repo
      apt_repository: repo='deb http://mirrors.ripple.com/ubuntu/ trusty stable contrib'
    - name: Install apt repo key
      apt_key: url=http://mirrors.ripple.com/mirrors.ripple.com.gpg.key
    - name: Install rippled
      apt: update_cache=true name=rippled
    - name: Make rippled data directories
      file: state=directory owner=rippled group=rippled path=/mnt/rippled/db/
    - name: Make rippled log directory
      file: state=directory owner=rippled group=rippled path=/mnt/rippled/log/

    - include: ../tasks/reconfigure-rippled.yml

    - name: Sleep for 30 seconds
      command: sleep 30
